server:
  port: 8080  #???
  address: localhost #ip???
  servlet:
    context-path: /springbootlearn

spring:
  profiles:
    active: dev  #

  thymeleaf:
    cache: false   #
    check-template-location: true  #
    servlet:
      content-type: text/html
    enabled: true #
    encoding: utf-8 #
    prefix: classpath:/templates/   #
    mode: HTML5   #
    suffix: .html #
  mvc:
    static-path-pattern: classpath:/static/  #



mybatis:
  type-aliases-package: com.hdc.springbootlearn.bean
  mapper-locations: classpath:/mappers/*.xml